### ISSUE TITLE
Account blocked 

### ISSUE THREAD

**Issue by anagrou** [breuerfelix/instapy-gui#113]
Hello,

I was wondering what should I use to don't get blocked in the Instagram browser. After the script has been executed and stopped I can't use my Instagram on the browser, only on the mobile phone. It always gives the error that I can't do the action at the moment and to try later on. I can't access messages, like, post, anything. 

Is it because of the IP? How long will I have to wait? 

Furthermore, Shall I use the quota supervisor? Does it helps? 

Looking forward to hear from you, many thanks!

**Comment by breuerfelix** [comment]
Hey,

well this is due to InstaPy ... instagram is lately blocking / shadow banning accounts using bots if the actions are suspicious.  
i think that you never ever used your browser for instagram before and suddenly do ALOT with the browser which is really suspicious.

you should stop using the bot and wait some weeks. test if you are able to like pictures in the browser once a while, if this is working again, start using instagram through your browser on a daily basis, and start botting for like 5 minutes every 2-3 days and increase the volume.

this MIGHT work but also might fail... no one knows :)

botting is not as easy as it used to be :D
