### ISSUE TITLE
How do i make it run 24/7 with sleep scheduled 

### ISSUE THREAD

**Issue by verobin2237** [breuerfelix/instapy-gui#115]
I'm trying to find a way to make it run 24/7 so that the session never ends. Obviously with sleep scheduled so that i don't get my Instagram account suspended ...is there any way?
my bot is raspberry pi btw

**Comment by breuerfelix** [comment]
this is a feature i started implementing but never actually finished.

the reason is pretty simple, there were more and more bugs in instapy i had to fix and i havent gotten any further in the gui stuff...

if you are a little programmer there is one simple solution, you just get an access token to instapy.io and have a look at the network tab which post request the browser does when pressing the start button. then you just do this request via cronjob :)

**Comment by 01CodeLT** [comment]
@breuerfelix Is there any documentation on what endpoints are available? I can't see any post requests in the dev tools, it all seems to be working through web sockets in the dashboard.

**Comment by breuerfelix** [comment]
https://github.com/breuerfelix/instapy-gui/blob/master/services/socket/index.js  this is the websocket file. yeah unfortunately this is all done via sockets cause thats the only way to see logs live. well i could have streamed only the logs but nvm :D

https://github.com/breuerfelix/instapy-gui/blob/master/services/auth/index.js this is a REST endpoint to issue a JWT which is needed for the socket :)

**Comment by 01CodeLT** [comment]
Thanks @breuerfelix. For those coming back here for an answer, here's a very basic PHP Laravel example. You'll likely want to add your own checks to see if the bot is already running etc, I used this package to easily connect to the socket - https://github.com/Textalk/websocket-php

        // Get instapy JWT
        $response = Http::post('https://auth.instapy.io/login', [
             'username' => 'instapy username',
             'password' => 'instapy password',
        ])->json();

        if(!isset($response['error'])) {
             $instapyToken = $response['token'];
        } else {
             throw new \ErrorException('Instapy login error: ' . $response['error']);
        }

        // Connect to socket
        $client = new \WebSocket\Client("wss://socket.instapy.io/", [
            'timeout' => 60,
            'headers' => [
                'origin' => 'yourdomain.co.uk',
                'Authorization' => 'Bearer ' . $instapyToken
            ],
        ]);

        // Login to socket
        $client->send(json_encode([
            "handler" => "register",
            "type" => "app"
        ]));

        // Send start request
        $client->send(json_encode([
            "handler" => "bot",
            "start" => true,
            "namespace" => "follow-users", //Template to run
            "setting" => "headless-instagram-login", //Setting to use
            "bot" => "instapy_test_server" //Bot to run the template on
        ]));
        echo $client->receive();
        $client->close();

**Comment by breuerfelix** [comment]
@01CodeLT pretty awesome! i think about making a new folder called user-scripts and add that as a little example because some people wanted that :)

the problem why i didnt implement it yet is that your script is pretty slim etc but i would need to make a frontend for that :D store stuff in DB, program a backend scheduler etc... so yeah its easier to trigger it yourself as you did!

btw i never used PHP so one questions i got here is: why do you need the backspace ? like `new \WebSocket\Client` that seems pretty weird syntax to me :D

**Comment by 01CodeLT** [comment]
@breuerfelix Yeah that makes sense! It's just the way [namespaces ](https://www.php.net/manual/en/language.namespaces.importing.php)work in PHP, I copied that code from within a class. Without the backslash it would think I'm trying to access a class within the same namespace. 

I could've just added `use WebSocket\Client` at the top of the class and then I could use it like this `Client("wss://socket.instapy.io/")` which looks nicer. I generally just prefer doing it the other way as it's clearer and prevents interference between classes.
