### ISSUE TITLE
"bot.py" + \Python38\lib\contextlib.py" +  ("generator didn't yield") from None

### ISSUE THREAD

**Issue by Rzbck** [breuerfelix/instapy-gui#125]
Hey  Hey ! 

Today i try to build more than one bot in W10 with ConEmu 

![image](https://user-images.githubusercontent.com/10966796/95230796-9c4a3d80-0802-11eb-9075-9ebb2ce61868.png)

for each Bot i create a new folder and a new installation with SetupBat

![image](https://user-images.githubusercontent.com/10966796/95229796-50e35f80-0801-11eb-8cb2-c7d8d46d04a4.png)
![image](https://user-images.githubusercontent.com/10966796/95230061-a3bd1700-0801-11eb-83ac-5f5c3e3d9e8e.png)

The first Bot is ok (Just a redunding problem with cookies and find login buttons like always but it work)
For the seconds Bot (BOT2) i always have this messages

![image](https://user-images.githubusercontent.com/10966796/95229998-8be59300-0801-11eb-8fdd-6807ead46c2b.png)

if you have some idea to resolve this issues it can be interesting ^^

**Comment by Teknival** [comment]
Yes I Have the same, its a new bug from cookies asking when the bot open the browser.. 

Cookie file not found, creating cookie...
INFO [2020-10-07 02:28:21] User]  Timed out with failure while explicitly waiting until title contains 'Login' string!

INFO [2020-10-07 02:29:00] [User]  Timed out with failure while explicitly waiting until visibility of element located!

**********************************************************************
If raising an issue, please also upload the file located at:
C:\Users\alexa\AppData\Local\Temp\20201007-022906.html
**********************************************************************

**Comment by breuerfelix** [comment]
Hey! this error is definitely something about instapy and not instapy-gui. Seems like instapy-gui is starting it correctly, then it shuts down because of the login error and then the exception occurs.

it would be pretty cool to open this issue in instapy again (you only need to provide infos from the bot which is not working).  also try starting it alone without the other one, the issue should persist right ?

**Comment by Rzbck** [comment]
The @Teknival  issus is not the same has my issue @breuerfelix  ^^ you think both of them are instapy issus ? 
anyway I have some idea of improvement of instapy GUI if you are open for that !

**Comment by breuerfelix** [comment]
@Rzbck yep yours is the same one :) not related to instapy-gui :) because it just handles the start and stop of the bot, but if the bot is started once, then everything is related to instapy itself.

of course ! just open a new issue and let me know :) well i do not have that much time imrpoving instapy gui anymore but maybe in the future. best would be, if you would implement the improvement yourself and make a PR if you are a coder :) but anyways, it is always good to hear improvement even if i am not able to implement it, but it helps for future other projects !
