### ISSUE TITLE
Unfollow does not work

### ISSUE THREAD

**Issue by rsingh-27** [breuerfelix/instapy-gui#35]
Hi I am trying to implement unfollow it doesn't work it throws an error in the console
here is the error
![Screenshot 2019-06-13 at 10 11 15 PM](https://user-images.githubusercontent.com/8249450/59451273-b4859480-8e28-11e9-847f-5df22f3c4b2e.png)

My parameters

![Screenshot 2019-06-13 at 10 10 52 PM](https://user-images.githubusercontent.com/8249450/59451298-c404dd80-8e28-11e9-86b6-0d89b542878b.png)

**Comment by breuerfelix** [comment]
I tried to reproduce this error BUT I can't do it, because I don't have anything to unfollow ...
and from reading the source code I really can't image where this happens...
it must happen in the file `unfollow_utils.py` and in the function `unfollow`.

its an error from instapy and not instapy Gui.

could you make a simple Quickstart script with the values you provided here and try it out ?

**Comment by rsingh-27** [comment]
@breuerfelix okay ill do that, I think this is an issue with chrome driver, it would be a good ad on if you let people choose firefix selenium driver by some toggle switch

**Comment by breuerfelix** [comment]
right now I got some major changes to completely get away from docker.

this will be finished in the next 1-2 weeks. after that ill implement the driver switch :)

**Comment by breuerfelix** [comment]
@rsingh-27 could you try the unfollow with the new version to see if the error still persists ?
